version: '3.8'

services:
  # 1. Сборщик трассировок OTel
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.95.0
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./config/otelcol-config.yaml:/etc/otelcol-config.yaml
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
    depends_on:
      - jaeger

  # 2. Хранилище трасс и UI для поиска улик
  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686" # Jaeger UI

  # 3. Сервис обработки заказов (Fault Transition)
  checkoutservice:
    image: ghcr.io/open-telemetry/demo:1.8.0-checkoutservice
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
    ports:
      - "50050:50050"
    depends_on:
      - otel-collector

  # 4. Платежный сервис (Crash Site)
  paymentservice:
    image: ghcr.io/open-telemetry/demo:1.8.0-paymentservice
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "50051:50051"
    depends_on:
      - otel-collector
